version: "3.4"
services:
  app:
    build:
      context: ./docker/app
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - .:/var/www
    env_file: .env
    container_name: lan_manager_app
  server:
    build:
      context: ./docker/server
      dockerfile: server.dockerfile
    working_dir: /var/www
    volumes:
      - ./certs:/etc/nginx/certs
      - .:/var/www
    env_file: .env
    ports:
      - 80:80
      - 443:443
    container_name: lan_manager_server
  database:
    build:
      context: ./docker/db
      dockerfile: db.dockerfile
    volumes:
      - db:/var/lib/mysql
    env_file: .env
    ports:
        - "3306:3306"
    container_name: lan_manager_database
volumes:
  db:
    name: lan_manager_db
